---
- name: create build directory
  file: 
    path: /opt/src/ 
    state: directory
    owner: "{{ operator }}"
    group: "{{ operator }}"
  sudo: yes

- name: fetch libreswan
  get_url: 
    url: https://download.libreswan.org/libreswan-3.12.tar.gz 
    dest: /opt/src/libreswan-3.12.tar.gz

- name: expand libreswan tarball
  unarchive: 
    creates: /opt/src/libreswan-3.12 
    copy: no
    src: /opt/src/libreswan-3.12.tar.gz 
    dest: /opt/src

- name: build libreswan
  shell: make programs 
  args:
    chdir: /opt/src/libreswan-3.12
    creates: /opt/src/libreswan-3.12/OBJ.linux.x86_64

- name: install libreswan
  command: make install
  args:
    chdir: /opt/src/libreswan-3.12
    creates: /usr/local/sbin/ipsec
  sudo: yes

