---
- name: Apply ipsec configuration
  template: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}" 
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: "ipsec.conf.j2", dest: "/etc/ipsec.conf" }
    - { src: "ipsec.secrets.j2", dest: "/etc/ipsec.secrets", mode: "0600" }
  sudo: yes
  notify:
    - Restart ipsec

- name: Prepare NSS cert db
  shell: |
    echo > /var/tmp/libreswan-nss-pwd
    /usr/bin/certutil -N -f /var/tmp/libreswan-nss-pwd -d /etc/ipsec.d
    /bin/rm -f /var/tmp/libreswan-nss-pwd
  args:
    creates: /etc/ipsec.d/cert8.db
  sudo: yes
  notify:
    - Restart ipsec
