---
- name: Restart ipsec
  service:
    name: ipsec
    state: restarted
  sudo: yes

- name: Restart xl2tpd
  service:
    name: xl2tpd
    state: restarted
    pattern: xl2tpd
  sudo: yes

- name: Reload sysctl
  command: /sbin/sysctl -p 
  sudo: yes

